name: ML1_7_pipelines
channels:
  - defaults
dependencies:
  - ipykernel=6.25.0
  - ipython=8.15.0
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - pandas=2.1.1
  - scikit-learn=1.3.0
  - seaborn=0.12
